name: Matlab Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Octave and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y octave octave-image octave-io

    - name: Run Tests
      run: |
        octave --eval "source('tests/test_measure_LCD.m'); test_measure_LCD();"
